### PR TITLE
FLOE-208: Adding overview panel to feedback demo

### PR DESCRIPTION
**Pull request by jobara**
Also performed some textual and link updates to the metadata authoring tool's overview panel to make things more consistent and accurate. Some minor refactoring to put the shared css into the shared directory.

http://issues.fluidproject.org/browse/FLOE-208

### CODE REVIEW

**Comment by cindyli** [comment]
In the feedback demo when the overview panel is closed, the black star button is stretched out of the bottom line of the feedback tool bar, which doesn't look good. Is that intentional? Shall it be shorter?

**Comment by cindyli** [comment]
Some issues with the overview panel responding to UIO in the feedback demo (The metadata demo doesn't have UIO integrated yet):
1. Keep the overview panel open;
2. The change on the line spacing does not get applied to the content on the overview panel;
3. Switching to any high contrast theme causes - 1) The happy face, sad face and the request font icons somehow show up in the "instruction" section on the overview panel, as well as the feedback toolbar where they belong to; 2) The circles around links for "demo code", "design", "get metadata" disappear. The 2) is reproducible in the infusion demos. We need to find out with designers if it's intentional or a bug.

**Comment by jobara** [comment]
@cindyli I've filed the contrast theme issue for the link icons against infusion http://issues.fluidproject.org/browse/FLUID-5500

**Comment by jobara** [comment]
@cindyli I've addressed the comments you've left including:
1. Adjusting the size and position of the overview panel icon
2. Fixing the line spacing in the overview panel to work with UIO
3. Improving the look and consistency of the icons used in the instructions.

**Comment by cindyli** [comment]
Merged into the project repo @ f2cbec03543957db0af482d433508117b576014b

**Pull request merged**
