### PR TITLE
FLOE-193

### PR DESCRIPTION
**Pull request by jobara**
Implemented the "top bar" of the feedback tool. The styling is done without Foundation, although it does require normalize.css

The demo itself uses foundation, and contains some overrides to maintain the feedback tools styles.

The component for the feedback too at the moment doesn't do much beside setup with the template. The functionality will come in later work on other jiras.

http://issues.fluidproject.org/browse/FLOE-193

### CODE REVIEW

**Comment by cindyli** [comment]
"feedback.html" can be named as "index.html" since it's already in feedback folder.

**Comment by cindyli** [comment]
The icons for happy face, sad face, request buttons are not shown and other icons look different from the wireframe. Can you check if the correct font icon files are used?

**Comment by cindyli** [comment]
The file permission for src/css/fonts/floe-metadata.eot and src/css/fonts/floe-metadata.ttf is 755. They should be 644.

**Comment by jobara** [comment]
The icons seem fine for me, maybe something is cached on your side?

**Comment by cindyli** [comment]
You are right, it's a caching issue.

**Comment by cindyli** [comment]
Merged @ e5d6b055179c82e25e72139e92b34eb30a985c32

**Pull request merged**
